version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/personal
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/system_reload.sh
      timeout: 6000
      runas: ubuntu
    - location: scripts/migrate.sh
      timeout: 6000
      runas: ubuntu