# Generated by Django 3.2.6 on 2021-08-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
