# Generated by Django 3.2.6 on 2021-08-09 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0003_course_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='promotor',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
