# Generated by Django 3.2.6 on 2021-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0004_auto_20210809_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('university_location', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_publish', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
