# Generated by Django 3.2.6 on 2021-08-11 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_level',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
