# Generated by Django 3.2.6 on 2021-08-16 15:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0006_education_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdesc_experience', to='personaldata.experience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
