# Generated by Django 3.2.6 on 2021-08-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0009_aboutdesc_is_publish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
