# Generated by Django 3.2.6 on 2021-10-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0011_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='end_date',
            new_name='date',
        ),
    ]
