# Generated by Django 3.2.6 on 2021-10-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0012_rename_end_date_projects_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='short_line',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
