# Generated by Django 3.2.6 on 2021-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0013_auto_20211002_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='journal_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
