# Generated by Django 3.2.6 on 2021-10-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0014_projects_journal_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('icon_class_name', models.CharField(max_length=50)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaldata.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
