# Generated by Django 3.2.6 on 2021-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0015_stacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacks',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='stacks',
            field=models.ManyToManyField(blank=True, to='personaldata.Stacks'),
        ),
    ]
