# Generated by Django 3.2.6 on 2021-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0016_auto_20211004_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='stacks',
            name='stack_type',
            field=models.CharField(choices=[('LANGUAGE', 'Programming Language'), ('FRAMEWORK', 'Framework'), ('PLATFORM', 'Platform')], default='LANGUAGE', max_length=20),
        ),
    ]
