# Generated by Django 3.2.6 on 2021-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0017_stacks_stack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='stacks',
            field=models.ManyToManyField(to='personaldata.Stacks'),
        ),
    ]
