# Generated by Django 3.2.6 on 2021-10-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personaldata', '0018_alter_projects_stacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
